HTTP_USERNAME = "{{ buildbot_credentials['http-user'] }}"
HTTP_PASSWORD = "{{ buildbot_credentials['http-pass'] }}"
SLAVE_PASSWORD = "{{ buildbot_credentials['slave-pass'] }}"
CHANGE_PASSWORD = "{{ buildbot_credentials['change-pass'] }}"
GITHUB_DOC_TOKEN = "{{ buildbot_credentials['gh-doc-token'] }}"
HOMU_BUILDBOT_SECRET = "{{ buildbot_credentials['homu-secret'] }}"
GITHUB_STATUS_TOKEN = "{{ buildbot_credentials['gh-status-token'] }}"
