#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

declare -a builders=("android" "android-x86" "linux-dev" "linux-nightly" "linux-rel-css"
                     "linux-rel-intermittent" "linux-rel-nogate"
                     "linux-rel-wpt" "android-nightly" "arm32" "arm64")

for builder in "${builders[@]}"
do
  rm -rf "/home/servo/buildbot/slave/${builder}/build/target/"
done
