#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

declare -a builders=("linux-rel-css" "linux-rel-nogate" "linux-rel-wpt")

for builder in "${builders[@]}"
do
  rm -rf "/home/servo/buildbot/slave/${builder}/build/target/"
done
