#!/usr/bin/env sh

install_salt () {
    set -o errexit
    set -o nounset

    if [ "$#" -lt 1 ]; then
        printf >&2 "usage: $0 os_name\n"
        exit 1
    fi
    OS_NAME="$1"

    # Ensure that pinned versions match as closely as possible
    if [ "${OS_NAME}" = "linux" ]; then
        printf "$0: installing salt for Linux\n"
        # Use Trusty (Ubuntu 14.04) on Travis
        curl https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.5.8/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
        printf 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.5.8 trusty main\n' | sudo tee -a /etc/apt/sources.list >/dev/null
        sudo apt-get -y update
        sudo apt-get -y install salt-minion=2015.5.8+ds-1
    elif [ "${OS_NAME}" = "osx" ]; then
        printf "$0: installing salt for Mac OS X\n"
        brew update
        brew install https://raw.githubusercontent.com/Homebrew/homebrew/86efec6695b019762505be440798c46d50ebd738/Library/Formula/saltstack.rb
    else
        printf >&2 "$0: unknown operating system ${OS_NAME}\n"
        exit 1
    fi
}

install_salt "$@"
