#!/usr/bin/env sh

set -o errexit
set -o nounset

install_salt () {
    # Ensure that pinned versions match as closely as possible
    if [ "${OS_NAME}" = "linux" ]; then
        printf "$0: installing salt for Linux\n"
        # Use Trusty (Ubuntu 14.04) on Travis
        curl https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.8.1/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
        printf 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.8.1 trusty main\n' | sudo tee -a /etc/apt/sources.list >/dev/null
        sudo apt-get -y update
        sudo apt-get -y install salt-minion=2015.8.1+ds-1
    elif [ "${OS_NAME}" = "osx" ]; then
        printf "$0: installing salt for Mac OS X\n"
        brew update
        brew install https://raw.githubusercontent.com/Homebrew/homebrew/74bc5ef500fe2242258b672a5e96c5429fc4792f/Library/Formula/saltstack.rb
    else
        printf >&2 "$0: unknown operating system ${OS_NAME}\n"
        exit 1
    fi
}

configure_salt () {
    printf "$0: copying Salt minion configuration from ${TEMPORARY_CONFIG_DIR}\n"
    sudo mkdir -p /etc/salt
    sudo cp "${FORCE_FLAG}" -- "${TEMPORARY_CONFIG_DIR}/minion" /etc/salt/minion
}

OPTIONS=$(getopt 'c:F' "$@")

eval set -- "${OPTIONS}"

TEMPORARY_CONFIG_DIR=""
FORCE_FLAG=""
OS_NAME=""

while true; do
    case "$1" in
        -c)
            shift
            TEMPORARY_CONFIG_DIR="$1"
            shift
            ;;
        -F)
            FORCE_FLAG="-f"
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [ "$#" -lt 1 ]; then
    printf >&2 "usage: $0 [-c <config_dir> [-F]] [--] os_name\n"
    exit 1
fi

OS_NAME="$1"
install_salt

if [ -n "${TEMPORARY_CONFIG_DIR}" ]; then
    configure_salt
fi
