#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if [[ "$#" < 1 ]]; then
  printf >&2 "usage: $0 os_name\n"
  exit 1
fi

# Ensure that pinned versions match as closely as possible

OS_NAME="$1"
if [[ "${OS_NAME}" == "linux" ]]; then
  printf "$0: installing salt for Linux\n"
  # Use Trusty (Ubuntu 14.04) on Travis
  curl https://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
  printf 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/2015.5 trusty main\n' | sudo tee -a /etc/apt/sources.list >/dev/null
  sudo apt-get -y update
  sudo apt-get -y install salt-minion=2015.5.6+ds-1
elif [[ "${OS_NAME}" == "osx" ]]; then
  printf "$0: installing salt for Mac OS X\n"
  brew update
  brew install https://raw.githubusercontent.com/Homebrew/homebrew/86efec6695b019762505be440798c46d50ebd738/Library/Formula/saltstack.rb
else
  printf >&2 "$0: unknown operating system ${OS_NAME}\n"
  exit 1
fi
