#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

declare -a builders=("mac-dev-unit" "mac-nightly" "mac-rel-css" "mac-rel-css1"
                     "mac-rel-css2" "mac-rel-intermittent" "mac-rel-wpt1"
                     "mac-rel-wpt2" "mac-rel-wpt3" "mac-rel-wpt4")

declare -a targets=("doc" "release" "geckolib" "debug")

for builder in "${builders[@]}"
do
  for target in "${targets[@]}"
  do
    rm -rf "/Users/servo/buildbot/slave/${builder}/build/target/${target}"
  done
done